# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libexceptions', [dirname(__file__)])
        except ImportError:
            import _libexceptions
            return _libexceptions
        if fp is not None:
            try:
                _mod = imp.load_module('_libexceptions', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libexceptions = swig_import_helper()
    del swig_import_helper
else:
    import _libexceptions
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libexceptions.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _libexceptions.SwigPyIterator_value(self)
    def incr(self, n=1): return _libexceptions.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _libexceptions.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _libexceptions.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _libexceptions.SwigPyIterator_equal(self, *args)
    def copy(self): return _libexceptions.SwigPyIterator_copy(self)
    def next(self): return _libexceptions.SwigPyIterator_next(self)
    def __next__(self): return _libexceptions.SwigPyIterator___next__(self)
    def previous(self): return _libexceptions.SwigPyIterator_previous(self)
    def advance(self, *args): return _libexceptions.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _libexceptions.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _libexceptions.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _libexceptions.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _libexceptions.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _libexceptions.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _libexceptions.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _libexceptions.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class envError(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, envError, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, envError, name)
    __repr__ = _swig_repr
    __swig_setmethods__["error"] = _libexceptions.envError_error_set
    __swig_getmethods__["error"] = _libexceptions.envError_error_get
    if _newclass:error = _swig_property(_libexceptions.envError_error_get, _libexceptions.envError_error_set)
    def __init__(self, *args): 
        this = _libexceptions.new_envError(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libexceptions.delete_envError
    __del__ = lambda self : None;
envError_swigregister = _libexceptions.envError_swigregister
envError_swigregister(envError)

class vfsError(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vfsError, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vfsError, name)
    __repr__ = _swig_repr
    __swig_setmethods__["error"] = _libexceptions.vfsError_error_set
    __swig_getmethods__["error"] = _libexceptions.vfsError_error_get
    if _newclass:error = _swig_property(_libexceptions.vfsError_error_get, _libexceptions.vfsError_error_set)
    def __init__(self, *args): 
        this = _libexceptions.new_vfsError(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libexceptions.delete_vfsError
    __del__ = lambda self : None;
vfsError_swigregister = _libexceptions.vfsError_swigregister
vfsError_swigregister(vfsError)

# This file is compatible with both classic and new-style classes.


