# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vertrex/dff-pro/dff/ui/gui/resources/idewizard.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IdeWizard(object):
    def setupUi(self, IdeWizard):
        IdeWizard.setObjectName(_fromUtf8("IdeWizard"))
        IdeWizard.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IdeWizard.setWindowIcon(icon)
        self.introPage = QtGui.QWizardPage()
        self.introPage.setObjectName(_fromUtf8("introPage"))
        self.gridLayout = QtGui.QGridLayout(self.introPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nameLabel = QtGui.QLabel(self.introPage)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.name = QtGui.QLineEdit(self.introPage)
        self.name.setObjectName(_fromUtf8("name"))
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.categoryLabel = QtGui.QLabel(self.introPage)
        self.categoryLabel.setObjectName(_fromUtf8("categoryLabel"))
        self.gridLayout.addWidget(self.categoryLabel, 1, 0, 1, 1)
        self.category = QtGui.QComboBox(self.introPage)
        self.category.setEditable(True)
        self.category.setObjectName(_fromUtf8("category"))
        self.gridLayout.addWidget(self.category, 1, 1, 1, 1)
        self.workLocationLabel = QtGui.QLabel(self.introPage)
        self.workLocationLabel.setObjectName(_fromUtf8("workLocationLabel"))
        self.gridLayout.addWidget(self.workLocationLabel, 2, 0, 1, 1)
        self.workLocationWidget = QtGui.QWidget(self.introPage)
        self.workLocationWidget.setObjectName(_fromUtf8("workLocationWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.workLocationWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.path = QtGui.QLineEdit(self.workLocationWidget)
        self.path.setObjectName(_fromUtf8("path"))
        self.horizontalLayout.addWidget(self.path)
        self.brwButton = QtGui.QPushButton(self.workLocationWidget)
        self.brwButton.setObjectName(_fromUtf8("brwButton"))
        self.horizontalLayout.addWidget(self.brwButton)
        self.gridLayout.addWidget(self.workLocationWidget, 2, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.typeLabel = QtGui.QLabel(self.introPage)
        self.typeLabel.setObjectName(_fromUtf8("typeLabel"))
        self.verticalLayout_2.addWidget(self.typeLabel)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.typeWidget = QtGui.QWidget(self.introPage)
        self.typeWidget.setObjectName(_fromUtf8("typeWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.typeWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.type_script = QtGui.QRadioButton(self.typeWidget)
        self.type_script.setChecked(True)
        self.type_script.setObjectName(_fromUtf8("type_script"))
        self.verticalLayout.addWidget(self.type_script)
        self.type_graphical = QtGui.QRadioButton(self.typeWidget)
        self.type_graphical.setObjectName(_fromUtf8("type_graphical"))
        self.verticalLayout.addWidget(self.type_graphical)
        self.type_driver = QtGui.QRadioButton(self.typeWidget)
        self.type_driver.setObjectName(_fromUtf8("type_driver"))
        self.verticalLayout.addWidget(self.type_driver)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.typeWidget, 3, 1, 1, 1)
        IdeWizard.addPage(self.introPage)
        self.descriptionPage = QtGui.QWizardPage()
        self.descriptionPage.setObjectName(_fromUtf8("descriptionPage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.descriptionPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.descriptionPage)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.description = QtGui.QTextEdit(self.descriptionPage)
        self.description.setObjectName(_fromUtf8("description"))
        self.verticalLayout_3.addWidget(self.description)
        IdeWizard.addPage(self.descriptionPage)
        self.authorPage = QtGui.QWizardPage()
        self.authorPage.setObjectName(_fromUtf8("authorPage"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.authorPage)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.authorPage)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.authorPage)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.authorPage)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.auth_fname = QtGui.QLineEdit(self.authorPage)
        self.auth_fname.setObjectName(_fromUtf8("auth_fname"))
        self.verticalLayout_4.addWidget(self.auth_fname)
        self.auth_lname = QtGui.QLineEdit(self.authorPage)
        self.auth_lname.setObjectName(_fromUtf8("auth_lname"))
        self.verticalLayout_4.addWidget(self.auth_lname)
        self.auth_mail = QtGui.QLineEdit(self.authorPage)
        self.auth_mail.setObjectName(_fromUtf8("auth_mail"))
        self.verticalLayout_4.addWidget(self.auth_mail)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.auth_fname.raise_()
        self.label_4.raise_()
        self.auth_lname.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.auth_mail.raise_()
        IdeWizard.addPage(self.authorPage)

        self.retranslateUi(IdeWizard)
        QtCore.QMetaObject.connectSlotsByName(IdeWizard)

    def retranslateUi(self, IdeWizard):
        IdeWizard.setWindowTitle(_translate("IdeWizard", "Integrated Development Environment Wizard", None))
        self.introPage.setTitle(_translate("IdeWizard", "General Information", None))
        self.introPage.setSubTitle(_translate("IdeWizard", "Fill all script information such as name, type and saving location.", None))
        self.nameLabel.setText(_translate("IdeWizard", "Name:", None))
        self.categoryLabel.setText(_translate("IdeWizard", "Category:", None))
        self.workLocationLabel.setText(_translate("IdeWizard", "Work location:", None))
        self.brwButton.setText(_translate("IdeWizard", "Browse", None))
        self.typeLabel.setText(_translate("IdeWizard", "Type:", None))
        self.type_script.setText(_translate("IdeWizard", "Script", None))
        self.type_graphical.setText(_translate("IdeWizard", "Graphical", None))
        self.type_driver.setText(_translate("IdeWizard", "Driver", None))
        self.descriptionPage.setTitle(_translate("IdeWizard", "Description", None))
        self.descriptionPage.setSubTitle(_translate("IdeWizard", "Describe here the goal of the module", None))
        self.label.setText(_translate("IdeWizard", "Module\'s description", None))
        self.authorPage.setTitle(_translate("IdeWizard", "Author informations", None))
        self.authorPage.setSubTitle(_translate("IdeWizard", "Fill all author\'s informations in order to complete header", None))
        self.label_2.setText(_translate("IdeWizard", "Author\'s first name:", None))
        self.label_3.setText(_translate("IdeWizard", "Author\'s last name:", None))
        self.label_4.setText(_translate("IdeWizard", "Author\'s electronic mail:", None))

import gui_rc
