# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vertrex/dff-pro/dff/ui/gui/resources/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 598)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuModule = QtGui.QMenu(self.menubar)
        self.menuModule.setObjectName(_fromUtf8("menuModule"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionLoadModule = QtGui.QAction(MainWindow)
        self.actionLoadModule.setObjectName(_fromUtf8("actionLoadModule"))
        self.actionOpen_evidence = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_evidence.setIcon(icon)
        self.actionOpen_evidence.setIconVisibleInMenu(True)
        self.actionOpen_evidence.setObjectName(_fromUtf8("actionOpen_evidence"))
        self.actionOpen_device = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/dev_hd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_device.setIcon(icon1)
        self.actionOpen_device.setIconVisibleInMenu(True)
        self.actionOpen_device.setObjectName(_fromUtf8("actionOpen_device"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/configure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon3)
        self.actionPreferences.setIconVisibleInMenu(True)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionMaximize = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/maximize.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMaximize.setIcon(icon4)
        self.actionMaximize.setIconVisibleInMenu(True)
        self.actionMaximize.setObjectName(_fromUtf8("actionMaximize"))
        self.actionFullscreen_mode = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/randr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFullscreen_mode.setIcon(icon5)
        self.actionFullscreen_mode.setIconVisibleInMenu(True)
        self.actionFullscreen_mode.setObjectName(_fromUtf8("actionFullscreen_mode"))
        self.actionNodeBrowser = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/view_detailed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNodeBrowser.setIcon(icon6)
        self.actionNodeBrowser.setIconVisibleInMenu(True)
        self.actionNodeBrowser.setObjectName(_fromUtf8("actionNodeBrowser"))
        self.actionShell = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/shell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShell.setIcon(icon7)
        self.actionShell.setIconVisibleInMenu(True)
        self.actionShell.setObjectName(_fromUtf8("actionShell"))
        self.actionPython_interpreter = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/interpreter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPython_interpreter.setIcon(icon8)
        self.actionPython_interpreter.setIconVisibleInMenu(True)
        self.actionPython_interpreter.setObjectName(_fromUtf8("actionPython_interpreter"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon9)
        self.actionHelp.setIconVisibleInMenu(True)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionIdeOpen = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/script-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIdeOpen.setIcon(icon10)
        self.actionIdeOpen.setIconVisibleInMenu(True)
        self.actionIdeOpen.setObjectName(_fromUtf8("actionIdeOpen"))
        self.actionBrowse_modules = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/module2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBrowse_modules.setIcon(icon11)
        self.actionBrowse_modules.setObjectName(_fromUtf8("actionBrowse_modules"))
        self.menuFile.addAction(self.actionOpen_evidence)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_device)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuModule.addAction(self.actionLoadModule)
        self.menuModule.addAction(self.actionBrowse_modules)
        self.menuModule.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuView.addAction(self.actionMaximize)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFullscreen_mode)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionNodeBrowser)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShell)
        self.menuView.addAction(self.actionPython_interpreter)
        self.menuView.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuModule.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Digital Forensics Framework", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuModule.setTitle(_translate("MainWindow", "Module", None))
        self.menuAbout.setTitle(_translate("MainWindow", "?", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Toolbar", None))
        self.actionAbout.setText(_translate("MainWindow", "About DFF ...", None))
        self.actionLoadModule.setText(_translate("MainWindow", "Load", None))
        self.actionLoadModule.setToolTip(_translate("MainWindow", "Load module", None))
        self.actionOpen_evidence.setText(_translate("MainWindow", "Open evidence", None))
        self.actionOpen_device.setText(_translate("MainWindow", "Open device", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize", None))
        self.actionFullscreen_mode.setText(_translate("MainWindow", "Fullscreen mode", None))
        self.actionNodeBrowser.setText(_translate("MainWindow", "Browser", None))
        self.actionShell.setText(_translate("MainWindow", "Console", None))
        self.actionShell.setToolTip(_translate("MainWindow", "Console", None))
        self.actionPython_interpreter.setText(_translate("MainWindow", "Live scripting", None))
        self.actionPython_interpreter.setToolTip(_translate("MainWindow", "Live scripting", None))
        self.actionHelp.setText(_translate("MainWindow", "Documentation", None))
        self.actionIdeOpen.setText(_translate("MainWindow", "IDE", None))
        self.actionIdeOpen.setToolTip(_translate("MainWindow", "Open the IDE", None))
        self.actionBrowse_modules.setText(_translate("MainWindow", "Browse", None))

import gui_rc
