# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vertrex/dff-pro/dff/ui/gui/resources/preferences.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName(_fromUtf8("PreferencesDialog"))
        PreferencesDialog.resize(458, 376)
        self.gridLayout_5 = QtGui.QGridLayout(PreferencesDialog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.buttonBox = QtGui.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_5.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.GlobalTab = QtGui.QWidget()
        self.GlobalTab.setObjectName(_fromUtf8("GlobalTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.GlobalTab)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.GlobalTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.noFootPrintCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.noFootPrintCheckBox.setObjectName(_fromUtf8("noFootPrintCheckBox"))
        self.gridLayout_4.addWidget(self.noFootPrintCheckBox, 0, 0, 1, 1)
        self.workingDirLabel = QtGui.QLabel(self.groupBox_2)
        self.workingDirLabel.setObjectName(_fromUtf8("workingDirLabel"))
        self.gridLayout_4.addWidget(self.workingDirLabel, 1, 0, 1, 1)
        self.workingDirPath = QtGui.QLineEdit(self.groupBox_2)
        self.workingDirPath.setObjectName(_fromUtf8("workingDirPath"))
        self.gridLayout_4.addWidget(self.workingDirPath, 1, 1, 1, 1)
        self.workingDirBrowse = QtGui.QPushButton(self.groupBox_2)
        self.workingDirBrowse.setObjectName(_fromUtf8("workingDirBrowse"))
        self.gridLayout_4.addWidget(self.workingDirBrowse, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.workDirWillCreate = QtGui.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.workDirWillCreate.setPalette(palette)
        self.workDirWillCreate.setWordWrap(True)
        self.workDirWillCreate.setObjectName(_fromUtf8("workDirWillCreate"))
        self.verticalLayout_7.addWidget(self.workDirWillCreate)
        self.workDirOK = QtGui.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.workDirOK.setPalette(palette)
        self.workDirOK.setWordWrap(True)
        self.workDirOK.setObjectName(_fromUtf8("workDirOK"))
        self.verticalLayout_7.addWidget(self.workDirOK)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.GlobalTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.historyLabel = QtGui.QLabel(self.groupBox)
        self.historyLabel.setObjectName(_fromUtf8("historyLabel"))
        self.gridLayout_2.addWidget(self.historyLabel, 1, 0, 1, 1)
        self.historyLineEdit = QtGui.QLineEdit(self.groupBox)
        self.historyLineEdit.setObjectName(_fromUtf8("historyLineEdit"))
        self.gridLayout_2.addWidget(self.historyLineEdit, 1, 1, 1, 1)
        self.historyToolButton = QtGui.QPushButton(self.groupBox)
        self.historyToolButton.setObjectName(_fromUtf8("historyToolButton"))
        self.gridLayout_2.addWidget(self.historyToolButton, 1, 2, 1, 1)
        self.noHistoryCheckBox = QtGui.QCheckBox(self.groupBox)
        self.noHistoryCheckBox.setObjectName(_fromUtf8("noHistoryCheckBox"))
        self.gridLayout_2.addWidget(self.noHistoryCheckBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.GlobalTab, _fromUtf8(""))
        self.LangTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LangTab.sizePolicy().hasHeightForWidth())
        self.LangTab.setSizePolicy(sizePolicy)
        self.LangTab.setObjectName(_fromUtf8("LangTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.LangTab)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.LangTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.langComboBox = QtGui.QComboBox(self.groupBox_3)
        self.langComboBox.setObjectName(_fromUtf8("langComboBox"))
        self.gridLayout.addWidget(self.langComboBox, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.tabWidget.addTab(self.LangTab, _fromUtf8(""))
        self.indexTab = QtGui.QWidget()
        self.indexTab.setToolTip(_fromUtf8(""))
        self.indexTab.setObjectName(_fromUtf8("indexTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.indexTab)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.indexTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/index_search_64x64.png")))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.indexTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.groupBox_4 = QtGui.QGroupBox(self.indexTab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.root_index_line = QtGui.QLineEdit(self.groupBox_4)
        self.root_index_line.setObjectName(_fromUtf8("root_index_line"))
        self.gridLayout_3.addWidget(self.root_index_line, 0, 1, 1, 1)
        self.root_index_button = QtGui.QPushButton(self.groupBox_4)
        self.root_index_button.setObjectName(_fromUtf8("root_index_button"))
        self.gridLayout_3.addWidget(self.root_index_button, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.index_name_line = QtGui.QLineEdit(self.groupBox_4)
        self.index_name_line.setObjectName(_fromUtf8("index_name_line"))
        self.gridLayout_3.addWidget(self.index_name_line, 1, 1, 1, 1)
        self.index_name_button = QtGui.QPushButton(self.groupBox_4)
        self.index_name_button.setObjectName(_fromUtf8("index_name_button"))
        self.gridLayout_3.addWidget(self.index_name_button, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.indexDirWillCreate = QtGui.QLabel(self.groupBox_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.indexDirWillCreate.setPalette(palette)
        self.indexDirWillCreate.setObjectName(_fromUtf8("indexDirWillCreate"))
        self.verticalLayout_4.addWidget(self.indexDirWillCreate)
        self.indexDirOK = QtGui.QLabel(self.groupBox_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.indexDirOK.setPalette(palette)
        self.indexDirOK.setObjectName(_fromUtf8("indexDirOK"))
        self.verticalLayout_4.addWidget(self.indexDirOK)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.tabWidget.addTab(self.indexTab, _fromUtf8(""))
        self.docTab = QtGui.QWidget()
        self.docTab.setObjectName(_fromUtf8("docTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.docTab)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_5 = QtGui.QGroupBox(self.docTab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.docAndHelpFullPathLabel = QtGui.QLabel(self.groupBox_5)
        self.docAndHelpFullPathLabel.setObjectName(_fromUtf8("docAndHelpFullPathLabel"))
        self.verticalLayout_9.addWidget(self.docAndHelpFullPathLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.docAndHelpFullPath = QtGui.QLineEdit(self.groupBox_5)
        self.docAndHelpFullPath.setObjectName(_fromUtf8("docAndHelpFullPath"))
        self.horizontalLayout_2.addWidget(self.docAndHelpFullPath)
        self.docAndHelpBrowse = QtGui.QPushButton(self.groupBox_5)
        self.docAndHelpBrowse.setObjectName(_fromUtf8("docAndHelpBrowse"))
        self.horizontalLayout_2.addWidget(self.docAndHelpBrowse)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_9.addWidget(self.label_6)
        self.helpNOK = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.helpNOK.setPalette(palette)
        self.helpNOK.setWordWrap(True)
        self.helpNOK.setObjectName(_fromUtf8("helpNOK"))
        self.verticalLayout_9.addWidget(self.helpNOK)
        self.helpOK = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.helpOK.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.helpOK.setFont(font)
        self.helpOK.setWordWrap(True)
        self.helpOK.setObjectName(_fromUtf8("helpOK"))
        self.verticalLayout_9.addWidget(self.helpOK)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.docTab, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences", None))
        self.groupBox_2.setTitle(_translate("PreferencesDialog", "Working environment", None))
        self.noFootPrintCheckBox.setText(_translate("PreferencesDialog", "No footprint", None))
        self.workingDirLabel.setText(_translate("PreferencesDialog", "DFF user\'s directory:", None))
        self.workingDirBrowse.setText(_translate("PreferencesDialog", "Browse", None))
        self.workDirWillCreate.setText(_translate("PreferencesDialog", "Provided path does not exist. You will be asked for creation on submit.", None))
        self.workDirOK.setText(_translate("PreferencesDialog", "Provided path is a readable directory.", None))
        self.groupBox.setTitle(_translate("PreferencesDialog", "History", None))
        self.historyLabel.setText(_translate("PreferencesDialog", "History file full path:", None))
        self.historyToolButton.setText(_translate("PreferencesDialog", "Browse", None))
        self.noHistoryCheckBox.setText(_translate("PreferencesDialog", "No history file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GlobalTab), _translate("PreferencesDialog", "Global", None))
        self.groupBox_3.setTitle(_translate("PreferencesDialog", "Interface language", None))
        self.label.setText(_translate("PreferencesDialog", "Use interface language:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LangTab), _translate("PreferencesDialog", "Language", None))
        self.label_5.setText(_translate("PreferencesDialog", "Please select in which directory you want to save indexed files. If those directories do not exist they will be created when changes will be applied.", None))
        self.groupBox_4.setTitle(_translate("PreferencesDialog", "Index files location", None))
        self.label_2.setText(_translate("PreferencesDialog", "Root index", None))
        self.root_index_button.setText(_translate("PreferencesDialog", "Browse", None))
        self.label_3.setText(_translate("PreferencesDialog", "Index name", None))
        self.index_name_button.setText(_translate("PreferencesDialog", "Browse", None))
        self.indexDirWillCreate.setText(_translate("PreferencesDialog", "Provided path does not exists, will ask for creation on submit.", None))
        self.indexDirOK.setText(_translate("PreferencesDialog", "Provided path is a readable directory.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.indexTab), _translate("PreferencesDialog", "Indexation", None))
        self.groupBox_5.setTitle(_translate("PreferencesDialog", "Help and documentation settings", None))
        self.docAndHelpFullPathLabel.setText(_translate("PreferencesDialog", "Full path of the help and documentation file:", None))
        self.docAndHelpBrowse.setText(_translate("PreferencesDialog", "Browse", None))
        self.label_6.setText(_translate("PreferencesDialog", "Please provide an help.qhc file along with an help.qch file at same directory level.", None))
        self.helpNOK.setText(_translate("PreferencesDialog", "Provided path is not a readable file.", None))
        self.helpOK.setText(_translate("PreferencesDialog", "Provided path is a readable file.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.docTab), _translate("PreferencesDialog", "Help and documentation", None))

import gui_rc
