# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vertrex/dff-pro/dff/ui/gui/resources/search_panel.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_searchPanel(object):
    def setupUi(self, searchPanel):
        searchPanel.setObjectName(_fromUtf8("searchPanel"))
        searchPanel.resize(289, 623)
        searchPanel.setBaseSize(QtCore.QSize(250, 0))
        self.verticalLayout_3 = QtGui.QVBoxLayout(searchPanel)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.quickSearch = QtGui.QGroupBox(searchPanel)
        self.quickSearch.setFlat(False)
        self.quickSearch.setCheckable(True)
        self.quickSearch.setObjectName(_fromUtf8("quickSearch"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.quickSearch)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.quickEdit = QtGui.QLineEdit(self.quickSearch)
        self.quickEdit.setObjectName(_fromUtf8("quickEdit"))
        self.horizontalLayout.addWidget(self.quickEdit)
        self.quickMode = QtGui.QComboBox(self.quickSearch)
        self.quickMode.setObjectName(_fromUtf8("quickMode"))
        self.quickMode.addItem(_fromUtf8(""))
        self.quickMode.addItem(_fromUtf8(""))
        self.quickMode.addItem(_fromUtf8(""))
        self.quickMode.addItem(_fromUtf8(""))
        self.quickMode.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.quickMode)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.quickSearch)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.imageType = QtGui.QToolButton(self.quickSearch)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/lphoto")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageType.setIcon(icon)
        self.imageType.setCheckable(True)
        self.imageType.setObjectName(_fromUtf8("imageType"))
        self.horizontalLayout_3.addWidget(self.imageType)
        self.soundType = QtGui.QToolButton(self.quickSearch)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/sound.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundType.setIcon(icon1)
        self.soundType.setCheckable(True)
        self.soundType.setObjectName(_fromUtf8("soundType"))
        self.horizontalLayout_3.addWidget(self.soundType)
        self.videoType = QtGui.QToolButton(self.quickSearch)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.videoType.setIcon(icon2)
        self.videoType.setCheckable(True)
        self.videoType.setObjectName(_fromUtf8("videoType"))
        self.horizontalLayout_3.addWidget(self.videoType)
        self.documentType = QtGui.QToolButton(self.quickSearch)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/document.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.documentType.setIcon(icon3)
        self.documentType.setCheckable(True)
        self.documentType.setObjectName(_fromUtf8("documentType"))
        self.horizontalLayout_3.addWidget(self.documentType)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(4, 100)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.quickSearch)
        self.advancedSearch = QtGui.QGroupBox(searchPanel)
        self.advancedSearch.setEnabled(True)
        self.advancedSearch.setFlat(False)
        self.advancedSearch.setCheckable(True)
        self.advancedSearch.setChecked(False)
        self.advancedSearch.setObjectName(_fromUtf8("advancedSearch"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.advancedSearch)
        self.verticalLayout_5.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.searchFiltersLayout = QtGui.QVBoxLayout()
        self.searchFiltersLayout.setObjectName(_fromUtf8("searchFiltersLayout"))
        self.verticalLayout_5.addLayout(self.searchFiltersLayout)
        self.verticalLayout_5.setStretch(0, 50)
        self.verticalLayout_3.addWidget(self.advancedSearch)
        self.groupBox = QtGui.QGroupBox(searchPanel)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fromRoot = QtGui.QCheckBox(self.groupBox)
        self.fromRoot.setObjectName(_fromUtf8("fromRoot"))
        self.verticalLayout.addWidget(self.fromRoot)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.searchProgress = QtGui.QProgressBar(searchPanel)
        self.searchProgress.setProperty("value", 0)
        self.searchProgress.setObjectName(_fromUtf8("searchProgress"))
        self.horizontalLayout_2.addWidget(self.searchProgress)
        self.matchedNodeLabel = QtGui.QLabel(searchPanel)
        self.matchedNodeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matchedNodeLabel.setObjectName(_fromUtf8("matchedNodeLabel"))
        self.horizontalLayout_2.addWidget(self.matchedNodeLabel)
        self.label_3 = QtGui.QLabel(searchPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2.setStretch(1, 30)
        self.horizontalLayout_2.setStretch(2, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.startButton = QtGui.QPushButton(searchPanel)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/viewmag")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon4)
        self.startButton.setIconSize(QtCore.QSize(18, 24))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_5.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(searchPanel)
        self.stopButton.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/mail_delete")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon5)
        self.stopButton.setIconSize(QtCore.QSize(18, 24))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_5.addWidget(self.stopButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)

        self.retranslateUi(searchPanel)
        QtCore.QMetaObject.connectSlotsByName(searchPanel)

    def retranslateUi(self, searchPanel):
        searchPanel.setWindowTitle(_translate("searchPanel", "Form", None))
        self.quickSearch.setTitle(_translate("searchPanel", "Quick search", None))
        self.quickMode.setItemText(0, _translate("searchPanel", "Wildcard", None))
        self.quickMode.setItemText(1, _translate("searchPanel", "Regexp", None))
        self.quickMode.setItemText(2, _translate("searchPanel", "Fuzzy", None))
        self.quickMode.setItemText(3, _translate("searchPanel", "Fixed", None))
        self.quickMode.setItemText(4, _translate("searchPanel", "Custom", None))
        self.label.setText(_translate("searchPanel", "Types : ", None))
        self.imageType.setText(_translate("searchPanel", "...", None))
        self.soundType.setText(_translate("searchPanel", "...", None))
        self.videoType.setText(_translate("searchPanel", "...", None))
        self.documentType.setText(_translate("searchPanel", "...", None))
        self.advancedSearch.setTitle(_translate("searchPanel", "Advanced search", None))
        self.groupBox.setTitle(_translate("searchPanel", "Options", None))
        self.fromRoot.setText(_translate("searchPanel", "Search from root", None))
        self.matchedNodeLabel.setText(_translate("searchPanel", "0", None))
        self.label_3.setText(_translate("searchPanel", "Found", None))
        self.startButton.setText(_translate("searchPanel", "Start", None))
        self.stopButton.setText(_translate("searchPanel", "Stop", None))

import gui_rc
