# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libdevices', [dirname(__file__)])
        except ImportError:
            import _libdevices
            return _libdevices
        if fp is not None:
            try:
                _mod = imp.load_module('_libdevices', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libdevices = swig_import_helper()
    del swig_import_helper
else:
    import _libdevices
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libdevices.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _libdevices.SwigPyIterator_value(self)
    def incr(self, n=1): return _libdevices.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _libdevices.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _libdevices.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _libdevices.SwigPyIterator_equal(self, *args)
    def copy(self): return _libdevices.SwigPyIterator_copy(self)
    def next(self): return _libdevices.SwigPyIterator_next(self)
    def __next__(self): return _libdevices.SwigPyIterator___next__(self)
    def previous(self): return _libdevices.SwigPyIterator_previous(self)
    def advance(self, *args): return _libdevices.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _libdevices.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _libdevices.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _libdevices.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _libdevices.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _libdevices.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _libdevices.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _libdevices.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Device(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Device, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Device, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libdevices.new_Device()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libdevices.delete_Device
    __del__ = lambda self : None;
    def blockDevice(self): return _libdevices.Device_blockDevice(self)
    def serialNumber(self): return _libdevices.Device_serialNumber(self)
    def model(self): return _libdevices.Device_model(self)
    def size(self): return _libdevices.Device_size(self)
Device_swigregister = _libdevices.Device_swigregister
Device_swigregister(Device)

class DeviceList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DeviceList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DeviceList, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libdevices.new_DeviceList()
        try: self.this.append(this)
        except: self.this = this
    def __iter__(self):
      for dev in self.deviceList:
            yield dev

    def __len__(self):
      return len(self.deviceList)

    def __getitem__(self, c):
      return self.deviceList[c]

    __swig_destroy__ = _libdevices.delete_DeviceList
    __del__ = lambda self : None;
DeviceList_swigregister = _libdevices.DeviceList_swigregister
DeviceList_swigregister(DeviceList)

class UDevice(Device):
    __swig_setmethods__ = {}
    for _s in [Device]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, UDevice, name, value)
    __swig_getmethods__ = {}
    for _s in [Device]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, UDevice, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _libdevices.new_UDevice(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libdevices.delete_UDevice
    __del__ = lambda self : None;
    def blockDevice(self): return _libdevices.UDevice_blockDevice(self)
    def serialNumber(self): return _libdevices.UDevice_serialNumber(self)
    def model(self): return _libdevices.UDevice_model(self)
    def size(self): return _libdevices.UDevice_size(self)
UDevice_swigregister = _libdevices.UDevice_swigregister
UDevice_swigregister(UDevice)

class UDevices(DeviceList):
    __swig_setmethods__ = {}
    for _s in [DeviceList]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, UDevices, name, value)
    __swig_getmethods__ = {}
    for _s in [DeviceList]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, UDevices, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libdevices.new_UDevices()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libdevices.delete_UDevices
    __del__ = lambda self : None;
    __swig_setmethods__["deviceList"] = _libdevices.UDevices_deviceList_set
    __swig_getmethods__["deviceList"] = _libdevices.UDevices_deviceList_get
    if _newclass:deviceList = _swig_property(_libdevices.UDevices_deviceList_get, _libdevices.UDevices_deviceList_set)
    def __iter__(self):
      for dev in self.deviceList:
            yield dev

    def __len__(self):
      return len(self.deviceList)

    def __getitem__(self, c):
      return self.deviceList[c]

UDevices_swigregister = _libdevices.UDevices_swigregister
UDevices_swigregister(UDevices)

class devList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, devList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, devList, name)
    __repr__ = _swig_repr
    def iterator(self): return _libdevices.devList_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _libdevices.devList___nonzero__(self)
    def __bool__(self): return _libdevices.devList___bool__(self)
    def __len__(self): return _libdevices.devList___len__(self)
    def pop(self): return _libdevices.devList_pop(self)
    def __getslice__(self, *args): return _libdevices.devList___getslice__(self, *args)
    def __setslice__(self, *args): return _libdevices.devList___setslice__(self, *args)
    def __delslice__(self, *args): return _libdevices.devList___delslice__(self, *args)
    def __delitem__(self, *args): return _libdevices.devList___delitem__(self, *args)
    def __getitem__(self, *args): return _libdevices.devList___getitem__(self, *args)
    def __setitem__(self, *args): return _libdevices.devList___setitem__(self, *args)
    def append(self, *args): return _libdevices.devList_append(self, *args)
    def empty(self): return _libdevices.devList_empty(self)
    def size(self): return _libdevices.devList_size(self)
    def clear(self): return _libdevices.devList_clear(self)
    def swap(self, *args): return _libdevices.devList_swap(self, *args)
    def get_allocator(self): return _libdevices.devList_get_allocator(self)
    def begin(self): return _libdevices.devList_begin(self)
    def end(self): return _libdevices.devList_end(self)
    def rbegin(self): return _libdevices.devList_rbegin(self)
    def rend(self): return _libdevices.devList_rend(self)
    def pop_back(self): return _libdevices.devList_pop_back(self)
    def erase(self, *args): return _libdevices.devList_erase(self, *args)
    def __init__(self, *args): 
        this = _libdevices.new_devList(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _libdevices.devList_push_back(self, *args)
    def front(self): return _libdevices.devList_front(self)
    def back(self): return _libdevices.devList_back(self)
    def assign(self, *args): return _libdevices.devList_assign(self, *args)
    def resize(self, *args): return _libdevices.devList_resize(self, *args)
    def insert(self, *args): return _libdevices.devList_insert(self, *args)
    def reserve(self, *args): return _libdevices.devList_reserve(self, *args)
    def capacity(self): return _libdevices.devList_capacity(self)
    __swig_destroy__ = _libdevices.delete_devList
    __del__ = lambda self : None;
devList_swigregister = _libdevices.devList_swigregister
devList_swigregister(devList)

# This file is compatible with both classic and new-style classes.


