# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LOCAL', [dirname(__file__)])
        except ImportError:
            import _LOCAL
            return _LOCAL
        if fp is not None:
            try:
                _mod = imp.load_module('_LOCAL', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LOCAL = swig_import_helper()
    del swig_import_helper
else:
    import _LOCAL
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LOCAL.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _LOCAL.SwigPyIterator_value(self)
    def incr(self, n=1): return _LOCAL.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _LOCAL.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _LOCAL.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _LOCAL.SwigPyIterator_equal(self, *args)
    def copy(self): return _LOCAL.SwigPyIterator_copy(self)
    def next(self): return _LOCAL.SwigPyIterator_next(self)
    def __next__(self): return _LOCAL.SwigPyIterator___next__(self)
    def previous(self): return _LOCAL.SwigPyIterator_previous(self)
    def advance(self, *args): return _LOCAL.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _LOCAL.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _LOCAL.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _LOCAL.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _LOCAL.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _LOCAL.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _LOCAL.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _LOCAL.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import dff.api.vfs.libvfs
import dff.api.exceptions.libexceptions
import dff.api.types.libtypes
import dff.api.events.libevents
class local(dff.api.vfs.libvfs.fso):
    """1"""
    __swig_setmethods__ = {}
    for _s in [dff.api.vfs.libvfs.fso]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, local, name, value)
    __swig_getmethods__ = {}
    for _s in [dff.api.vfs.libvfs.fso]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, local, name)
    __repr__ = _swig_repr
    def iterdir(self, *args):
        """
        iterdir(local self, std::string path, Node parent)

        1
        """
        return _LOCAL.local_iterdir(self, *args)

    def __init__(self): 
        """
        __init__(local self) -> local

        1
        """
        this = _LOCAL.new_local()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LOCAL.delete_local
    __del__ = lambda self : None;
    def vopen(self, *args):
        """
        vopen(local self, Node handle) -> int32_t

        Open a node.

        Param :
                * n : the node you want to open

        Return the opened file descriptor, or 0 if it failed.

        """
        return _LOCAL.local_vopen(self, *args)

    def vread(self, *args):
        """
        vread(local self, int fd, void * buff, unsigned int size) -> int32_t

        vread(self, int32_t fd, void rbuff, uint32_t size) -> int32_t

        Perform readings on an open node and returns the number of bytes which wereread.

        Params :
                * fd : the file descriptor of the node you want to read on.
                * rbuff : a pointer to an allocated buffer where the read bytes will be stored
                * size : the number of characters you want to read.

        Return the number of read characters.

        """
        return _LOCAL.local_vread(self, *args)

    def vclose(self, *args):
        """
        vclose(local self, int fd) -> int32_t

        Close an open file descriptor and make it available again for others
        openings.

        Return `0` if everything went fine, `0` otherwise.

        """
        return _LOCAL.local_vclose(self, *args)

    def vseek(self, *args):
        """
        vseek(local self, int fd, uint64_t offset, int whence) -> uint64_t

        vseek(self, int32_t fd, uint64_t offset, int32_t whence) -> uint64_t

        This method is used to change position within an open node (i.e. modifies the
        offset of the current position). The offset is set to 0 when the file is open.

        Throws a vfsError if something goes wrong (typically if the seeking position is
        after the end of the file).

        It takes three parameters :
                * a file descriptor of an open node
                * the offset where you want to seek
                * the third parameter is optional : it defines if the offset passed in second parameter is absolute or relative.

        Return an uint64_t

        """
        return _LOCAL.local_vseek(self, *args)

    def vwrite(self, *args):
        """
        vwrite(local self, int fd, void * buff, unsigned int size) -> int32_t

        Not used.

        """
        return _LOCAL.local_vwrite(self, *args)

    def status(self):
        """
        status(local self) -> uint32_t

        Return the status of the module.

        """
        return _LOCAL.local_status(self)

    def vtell(self, *args):
        """
        vtell(local self, int32_t fd) -> uint64_t

        Returns the current offset in a file.

        """
        return _LOCAL.local_vtell(self, *args)

    def start(self, *args):
        """
        start(local self, VMap args)

        This method is called when the module starts. It does the job the module
        is supposed to do. This method is declared as a pure virtual so each modules
        must reiplements it (see the developer's documentations for more details) in
        python or C++, depending on which language you choose.

        The parameter 'args' is a pointer to the arguments list which were passed to the
        module when it was launched. You can get them by using the method
         args->get("arg_name", &variable)
        where variable must be of the same type than the argument "arg_name"

        If you create nodes, you must not forget to call the method register_tree at
        the end of the module execution.

        If an error occured while getting a parameter, a envError exception is thrown.

        Params :
                * args : the list of arguments passed to the module.


        """
        return _LOCAL.local_start(self, *args)

local_swigregister = _LOCAL.local_swigregister
local_swigregister(local)

__dff_module_LOCAL_version__ = "1.0.0"

from dff.api.module.module import *
from dff.api.types.libtypes import *
from dff.api.vfs import vfs
class LOCAL(Module):
  """Add files from your drives to the VFS"""
  def __init__(self):
    Module.__init__(self, 'local', local)
    self.conf.addArgument({"input": Argument.Optional|Argument.Single|typeId.Node, 
                           "name": "parent", 
                           "description": "files or folders will be added as child(ren) of this node or as the root node by default",
                           "parameters": {"type": Parameter.Editable,
                           "predefined": [vfs.vfs().getnode("/")]}
                          })
    self.conf.addArgument({"input": Argument.Required|Argument.List|typeId.Path,  
                           "name": "path", 
                           "description": "Path to the files or folders located on your drives."})
    self.tags = "Connectors"

# This file is compatible with both classic and new-style classes.


